# Generated by Django 4.2.27 on 2025-12-24 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="제목"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "대진표 세션",
                "verbose_name_plural": "대진표 세션들",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(blank=True, max_length=50, verbose_name="게스트 이름"),
                ),
                (
                    "guest_gender",
                    models.CharField(blank=True, max_length=1, verbose_name="게스트 성별"),
                ),
                (
                    "guest_ntrp",
                    models.CharField(
                        blank=True, default="2.5", max_length=3, verbose_name="게스트 NTRP"
                    ),
                ),
                (
                    "timing",
                    models.CharField(
                        choices=[
                            ("full", "전체 참석"),
                            ("late", "늦게 참석"),
                            ("early", "일찍 퇴장"),
                            ("partial", "부분 참석"),
                        ],
                        default="full",
                        max_length=10,
                        verbose_name="참석 유형",
                    ),
                ),
                (
                    "start_round",
                    models.PositiveIntegerField(default=1, verbose_name="시작 라운드"),
                ),
                (
                    "end_round",
                    models.PositiveIntegerField(default=99, verbose_name="종료 라운드"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participations",
                        to="members.member",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="matchmaking.matchsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "참가자",
                "verbose_name_plural": "참가자들",
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveIntegerField(verbose_name="라운드")),
                ("court_number", models.PositiveIntegerField(verbose_name="코트 번호")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="matchmaking.matchsession",
                    ),
                ),
                (
                    "team_a_player1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_a1",
                        to="matchmaking.participant",
                    ),
                ),
                (
                    "team_a_player2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_a2",
                        to="matchmaking.participant",
                    ),
                ),
                (
                    "team_b_player1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_b1",
                        to="matchmaking.participant",
                    ),
                ),
                (
                    "team_b_player2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_b2",
                        to="matchmaking.participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "경기",
                "verbose_name_plural": "경기들",
                "ordering": ["round_number", "court_number"],
            },
        ),
    ]
