# Generated by Django 4.2.27 on 2025-12-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("date", models.DateField(verbose_name="날짜")),
                ("start_time", models.TimeField(verbose_name="시작 시간")),
                ("end_time", models.TimeField(verbose_name="종료 시간")),
                ("location", models.CharField(max_length=200, verbose_name="장소")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "google_event_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="구글 캘린더 ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="events",
                        to="members.member",
                        verbose_name="참석 멤버",
                    ),
                ),
            ],
            options={
                "verbose_name": "일정",
                "verbose_name_plural": "일정들",
                "ordering": ["date", "start_time"],
            },
        ),
    ]
