# Generated by Django 4.2.27 on 2025-12-24 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="recurrence_end_date",
            field=models.DateField(blank=True, null=True, verbose_name="반복 종료일"),
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurrence_children",
                to="schedule.event",
                verbose_name="원본 일정",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence_type",
            field=models.CharField(
                choices=[
                    ("none", "반복 없음"),
                    ("daily", "매일"),
                    ("weekly", "매주"),
                    ("custom", "사용자 정의"),
                ],
                default="none",
                max_length=10,
                verbose_name="반복 유형",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence_weekdays",
            field=models.CharField(blank=True, max_length=50, verbose_name="반복 요일"),
        ),
    ]
