# Generated by Django 4.2.27 on 2025-12-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "남성"), ("F", "여성")],
                        max_length=1,
                        verbose_name="성별",
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(default=0, verbose_name="구력(년)"),
                ),
                (
                    "ntrp",
                    models.CharField(
                        choices=[
                            ("1.0", "1.0"),
                            ("1.5", "1.5"),
                            ("2.0", "2.0"),
                            ("2.5", "2.5"),
                            ("3.0", "3.0"),
                            ("3.5", "3.5"),
                            ("4.0", "4.0"),
                            ("4.5", "4.5"),
                            ("5.0", "5.0"),
                            ("5.5", "5.5"),
                            ("6.0", "6.0"),
                            ("6.5", "6.5"),
                            ("7.0", "7.0"),
                        ],
                        default="2.5",
                        max_length=3,
                        verbose_name="NTRP",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "활동중"), ("inactive", "휴회중")],
                        default="active",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="연락처"),
                ),
                (
                    "joined_date",
                    models.DateField(auto_now_add=True, verbose_name="가입일"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "멤버",
                "verbose_name_plural": "멤버들",
                "ordering": ["name"],
            },
        ),
    ]
