# Generated by Django 4.2.27 on 2025-12-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="운영진"),
        ),
    ]
